FROM python:3.11.3-alpine

# ignore root user pip warning by default
ENV PIP_ROOT_USER_ACTION=ignore

RUN apk update
RUN apk add postgresql-dev 
RUN apk add gcc 
RUN apk add musl-dev
RUN apk add bash

WORKDIR /app
COPY . /app

EXPOSE 3000 
CMD ./scripts/setup.sh
